filegroup(
    name = "graph",
    srcs = [
        "graph.yaml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "example_fault_injection",
    srcs = [
        "delay_loop.yaml",
        "delay_receive.yaml",
        "drop_loop.yaml",
        "drop_receive.yaml",
    ],
    visibility = ["//visibility:public"],
)
