# This subsystem employs fail silent approach. If the upstream GPS location is invalid or lost,
# it will not publish any data.

nodes:
  # This node is responsible for loading the map from the onboard storage system.
  - name: map_loader
    subscribe:
      - topic: gps1
        valid_range: [0, 10]
        watchdog: 25
        nominal_callback:
          publish:
            - topic: map_data
              value_range: [10, 20]
              delay_range: [1, 2]
        invalid_input_callback:
          publish:
            - topic: map_data
              value_range: [20, 30]
              delay_range: [1, 2]

      - topic: gps2
        valid_range: [0, 10]
        watchdog: 25

        invalid_input_callback:
          fault:
            affect_publish:
              topic: map_data
              value: 30
              count: 1
        lost_input_callback:
          fault:
            affect_publish:
              topic: map_data
              drop: 1

      - topic: imu_data1
        valid_range: [0, 10]
        watchdog: 8
        lost_input_callback:
          fault:
            affect_publish:
              topic: map_data
              drop: 1

      - topic: imu_data2
        valid_range: [0, 10]
        watchdog: 8
        lost_input_callback:
          fault:
            affect_publish:
              topic: map_data
              drop: 1

  - name: road
    subscribe:
      - topic: map_data
        valid_range: [10, 20]
        watchdog: 25

        invalid_input_callback:
          fault:
            affect_publish:
              topic: road_data
              value: 30
              count: 2
        lost_input_callback:
          fault:
            affect_publish:
              topic: road_data
              drop: 2

      - topic: processed_camera_data1
        valid_range: [100, 200]
        watchdog: 7
        lost_input_callback:
          fault:
            affect_publish:
              topic: road_data
              drop: 5

      - topic: processed_camera_data2
        valid_range: [200, 300]
        watchdog: 7
        lost_input_callback:
          fault:
            affect_publish:
              topic: road_data
              drop: 5

      - topic: processed_camera_data5
        valid_range: [500, 600]
        watchdog: 7
        lost_input_callback:
          fault:
            affect_publish:
              topic: road_data
              drop: 5
              
      - topic: processed_camera_data8
        valid_range: [800, 900]
        watchdog: 7
        lost_input_callback:
          fault:
            affect_publish:
              topic: road_data
              drop: 5

    loop:
      period: 20
      callback:
        publish:
          - topic: road_data
            value_range: [20, 30]
            delay_range: [1, 2]

  - name: localization
    subscribe:
      - topic: gps1
        valid_range: [0, 10]
        watchdog: 10
        invalid_input_callback:
          fault:
            affect_publish:
              topic: localization_data
              value: 50
              count: 2

      - topic: gps2
        valid_range: [0, 10]
        watchdog: 10
        invalid_input_callback:
          fault:
            affect_publish:
              topic: localization_data
              value: 50
              count: 1
        lost_input_callback:
          fault:
            affect_publish:
              topic: localization_data
              drop: 1

    loop:
      period: 10
      callback:
        publish:
          - topic: localization_data
            value_range: [100, 200]
            delay_range: [1, 2]

  - name: terrain_analyzer
    subscribe:
      - topic: processed_lidar_data1
        valid_range: [100, 200]
        watchdog: 10
        invalid_input_callback:
          fault:
            affect_publish:
              topic: terrain_data
              drop: 1

      - topic: processed_lidar_data4
        valid_range: [400, 500]
        watchdog: 10
        invalid_input_callback:
          fault:
            affect_publish:
              topic: terrain_data
              drop: 1

      - topic: road_data
        valid_range: [20, 30]
        watchdog: 25
        invalid_input_callback:
          fault:
            affect_publish:
              topic: terrain_data
              value: 200
              count: 2
        lost_input_callback:
          fault:
            affect_publish:
              topic: terrain_data
              drop: 2
    
    loop:
      period: 10
      callback:
        publish:
          - topic: terrain_data
            value_range: [0, 100]
            delay_range: [3, 5]
