# This subsystem contains nodes with very high in degree and also forms a cycle with the perception subsystem.
# This subsystem has nodes that would crash due to invalid input data, to model user code that contains
# bugs and is not performing input sanitization.
nodes:
  - name: planner
    subscribe:
      - topic: lane_data
        valid_range: [10, 20]
        watchdog: 25
        nominal_callback:
          publish:
            - topic: trajectory
              value_range: [10, 20]
              delay_range: [1, 2]
        invalid_input_callback:
          publish:
            - topic: trajectory
              value_range: [20, 30]
              delay_range: [1, 2]
        lost_input_callback:
          publish:
            - topic: trajectory
              value_range: [20, 30]
              delay_range: [1, 2]

      - topic: traffic_light
        valid_range: [10, 20]
        watchdog: 25
        nominal_callback:
          # do nothing
        invalid_input_callback:
          # do nothing
        lost_input_callback:
          action:
            drop_event_for: 50

      - topic: imu_data1
        valid_range: [0, 10]
        watchdog: 8
        nominal_callback:
          # do nothing
        invalid_input_callback:
          publish:
            - topic: trajectory
              value_range: [20, 30]
              delay_range: [1, 2]
        lost_input_callback:
          publish:
            - topic: trajectory
              value_range: [20, 30]
              delay_range: [1, 2]

      - topic: imu_data2
        valid_range: [0, 10]
        watchdog: 8
        nominal_callback:
          # do nothing
        invalid_input_callback:
          publish:
            - topic: trajectory
              value_range: [20, 30]
              delay_range: [1, 2]
        lost_input_callback:
          publish:
            - topic: trajectory
              value_range: [20, 30]
              delay_range: [1, 2]

      - topic: tracks
        valid_range: [10, 20]
        watchdog: 25
        nominal_callback:
          # do nothing
        invalid_input_callback:
          action:
            crash: true
        lost_input_callback:
          action:
            drop_event_for: 50

      - topic: control_output
        valid_range: [10, 20]
        watchdog: 25
        nominal_callback:
          # do nothing
        invalid_input_callback:
          action:
            drop_event_for: 20
        lost_input_callback:
          action:
            drop_event_for: 20

    loop:
      period: 10
      callback:
        publish:
          - topic: capability
            value_range: [10, 20]
            delay_range: [1, 2]
