# This subsystem contains nodes with very high in degree and also forms a cycle with the perception subsystem.
# This subsystem has nodes that would crash due to invalid input data, to model user code that contains
# bugs and is not performing input sanitization.
nodes:
  - name: planner
    subscribe:
      - topic: lane_data
        valid_range: [10, 20]
        watchdog: 25
        lost_input_callback:
          fault:
            affect_publish:
              topic: trajectory
              drop: 3

      - topic: traffic_light
        valid_range: [10, 20]
        watchdog: 25
        lost_input_callback:
          fault:
            affect_publish:
              topic: trajectory
              drop: 3

      - topic: tracks
        valid_range: [10, 20]
        watchdog: 25

        lost_input_callback:
          fault:
            affect_publish:
              topic: trajectory
              drop: 3

      - topic: control_output
        valid_range: [10, 20]
        watchdog: 25

        lost_input_callback:
          fault:
            affect_publish:
              topic: trajectory
              drop: 3

    loop:
      period: 10
      callback:
        publish:
          - topic: capability
            value_range: [10, 20]
            delay_range: [1, 2]
          - topic: trajectory
            value_range: [10, 20]
            delay_range: [1, 2]
