# This subsystem has nodes that consume the most data from another subsystem (sensor),
# which allows us to model nodes with high in degree.
# The tracker node will also get stuck when some input is lost, to model user code that
# requires non-deterministic processing time to reconcile missing input data.
nodes:
  - name: lane_boundary
    subscribe:
      - topic: road_data
        valid_range: [20, 30]
        watchdog: 25
        invalid_input_callback:
          fault:
            affect_publish:
              topic: lane_data
              value: 40
              count: 2
        lost_input_callback:
          fault:
            affect_publish:
              topic: lane_data
              drop: 2

      - topic: processed_lidar_data1
        valid_range: [100, 200]
        watchdog: 15
        invalid_input_callback:
          fault:
            affect_publish:
              topic: lane_data
              drop: 2
        lost_input_callback:
          fault:
            affect_publish:
              topic: lane_data
              drop: 2

      - topic: processed_lidar_data2
        valid_range: [200, 300]
        watchdog: 15
        invalid_input_callback:
          fault:
            affect_publish:
              topic: lane_data
              drop: 2
        lost_input_callback:
          fault:
            affect_publish:
              topic: lane_data
              drop: 2

    loop:
      period: 20
      callback:
        publish:
          - topic: lane_data
            value_range: [10, 20]
            delay_range: [1, 2]

  - name: traffic_light
    # This node fails silently
    subscribe:
      - topic: lane_data
        valid_range: [10, 20]
        watchdog: 25
        nominal_callback:
          publish:
            - topic: traffic_light
              value_range: [10, 20]
              delay_range: [1, 2]

        invalid_input_callback:
          publish:
            - topic: traffic_light
              value_range: [20, 30]
              delay_range: [1, 2]

  - name: tracker
    # This nodes detects cars, pedestrians, and track them across time.
    # It is highly connected to sensor data.
    subscribe:
      - topic: processed_lidar_data1
        valid_range: [100, 200]
        watchdog: 15
        lost_input_callback:
          fault:
            affect_publish:
              topic: tracks
              drop: 5

      - topic: processed_lidar_data2
        valid_range: [200, 300]
        watchdog: 15
        lost_input_callback:
          fault:
            affect_publish:
              topic: tracks
              drop: 5

      - topic: processed_lidar_data3
        valid_range: [300, 400]
        watchdog: 15
        lost_input_callback:
          fault:
            affect_publish:
              topic: tracks
              drop: 5

      - topic: processed_lidar_data4
        valid_range: [400, 500]
        watchdog: 15
        lost_input_callback:
          fault:
            affect_publish:
              topic: tracks
              drop: 5

      - topic: processed_camera_data1
        valid_range: [100, 200]
        watchdog: 7
        lost_input_callback:
          fault:
            affect_publish:
              topic: tracks
              drop: 5

      - topic: processed_camera_data2
        valid_range: [200, 300]
        watchdog: 7
        lost_input_callback:
          fault:
            affect_publish:
              topic: tracks
              drop: 5

      - topic: processed_camera_data3
        valid_range: [300, 400]
        watchdog: 7
        lost_input_callback:
          fault:
            affect_publish:
              topic: tracks
              drop: 5

      - topic: processed_camera_data4
        valid_range: [400, 500]
        watchdog: 7
        lost_input_callback:
          fault:
            affect_publish:
              topic: tracks
              drop: 5
      
      - topic: processed_camera_data5
        valid_range: [500, 600]
        watchdog: 7
        lost_input_callback:
          fault:
            affect_publish:
              topic: tracks
              drop: 5

      - topic: processed_camera_data6
        valid_range: [600, 700]
        watchdog: 7
        lost_input_callback:
          fault:
            affect_publish:
              topic: tracks
              drop: 5

      - topic: processed_camera_data7
        valid_range: [700, 800]
        watchdog: 7
        lost_input_callback:
          fault:
            affect_publish:
              topic: tracks
              drop: 5

      - topic: processed_camera_data8
        valid_range: [800, 900]
        watchdog: 7
        lost_input_callback:
          fault:
            affect_publish:
              topic: tracks
              drop: 5

      - topic: traffic_light
        valid_range: [10, 20]
        watchdog: 25
        lost_input_callback:
          fault:
            affect_publish:
              topic: tracks
              drop: 5

      - topic: capability
        valid_range: [10, 20]
        watchdog: 15
        lost_input_callback:
          fault:
            affect_publish:
              topic: tracks
              drop: 3

    loop:
      period: 20
      callback:
        publish:
          - topic: tracks
            value_range: [10, 20]
            delay_range: [5, 8]

  - name: obstacle_detection
    subscribe:
      - topic: processed_camera_data5
        valid_range: [500, 600]
        watchdog: 10
        invalid_input_callback:
          fault:
            affect_publish:
              topic: obstacle_data
              drop: 4

      - topic: processed_camera_data7
        valid_range: [700, 800]
        watchdog: 10
        invalid_input_callback:
          fault:
            affect_publish:
              topic: obstacle_data
              drop: 4

      - topic: processed_lidar_data2
        valid_range: [200, 300]
        watchdog: 10
        invalid_input_callback:
          fault:
            affect_publish:
              topic: obstacle_data
              drop: 2
              
      - topic: processed_lidar_data4
        valid_range: [400, 500]
        watchdog: 10
        invalid_input_callback:
          fault:
            affect_publish:
              topic: obstacle_data
              drop: 2

    loop:
      period: 15
      callback:
        publish:
          - topic: obstacle_data
            value_range: [50, 100]
            delay_range: [1, 2]


  - name: sensor_fusion
    subscribe:
      - topic: processed_camera_data2
        valid_range: [200, 300]
        watchdog: 20
        invalid_input_callback:
          fault:
            affect_publish:
              topic: sensor_fusion_data
              drop: 3

      - topic: processed_camera_data4
        valid_range: [400, 500]
        watchdog: 20
        invalid_input_callback:
          fault:
            affect_publish:
              topic: sensor_fusion_data
              drop: 3
              
      - topic: processed_camera_data6
        valid_range: [600, 700]
        watchdog: 20
        invalid_input_callback:
          fault:
            affect_publish:
              topic: sensor_fusion_data
              drop: 3

      - topic: processed_camera_data8
        valid_range: [800, 900]
        watchdog: 20
        invalid_input_callback:
          fault:
            affect_publish:
              topic: sensor_fusion_data
              drop: 3

      - topic: processed_lidar_data1
        valid_range: [100, 200]
        watchdog: 20
        invalid_input_callback:
          fault:
            affect_publish:
              topic: sensor_fusion_data
              drop: 3

      - topic: processed_lidar_data2
        valid_range: [200, 300]
        watchdog: 20
        invalid_input_callback:
          fault:
            affect_publish:
              topic: sensor_fusion_data
              drop: 3

      - topic: processed_lidar_data3
        valid_range: [300, 400]
        watchdog: 20
        invalid_input_callback:
          fault:
            affect_publish:
              topic: sensor_fusion_data
              drop: 3

      - topic: imu_data1
        valid_range: [0, 10]
        watchdog: 25
        invalid_input_callback:
          fault:
            affect_publish:
              topic: sensor_fusion_data
              drop: 3

    loop:
      period: 20
      callback:
        publish:
          - topic: sensor_fusion_data
            value_range: [200, 300]
            delay_range: [2, 3]

  - name: visual_odometry
    subscribe:
      - topic: processed_camera_data3
        valid_range: [300, 400]
        watchdog: 7
        invalid_input_callback:
          fault:
            affect_publish:
              topic: visual_odometry_data
              drop: 1

      - topic: processed_camera_data6
        valid_range: [600, 700]
        watchdog: 7
        invalid_input_callback:
          fault:
            affect_publish:
              topic: visual_odometry_data
              drop: 1

      - topic: processed_camera_data7
        valid_range: [700, 800]
        watchdog: 7
        invalid_input_callback:
          fault:
            affect_publish:
              topic: visual_odometry_data
              drop: 1

    loop:
      period: 15
      callback:
        publish:
          - topic: visual_odometry_data
            value_range: [50, 100]
            delay_range: [1, 2]


  - name: motion_estimator
    subscribe:
      - topic: visual_odometry_data
        valid_range: [50, 100]
        watchdog: 25
        invalid_input_callback:
          fault:
            affect_publish:
              topic: motion_estimation_data
              value: 60
              count: 2
        lost_input_callback:
          fault:
            affect_publish:
              topic: motion_estimation_data
              drop: 2

      - topic: sensor_fusion_data
        valid_range: [200, 300]
        watchdog: 25
        invalid_input_callback:
          fault:
            affect_publish:
              topic: motion_estimation_data
              drop: 3
        lost_input_callback:
          fault:
            affect_publish:
              topic: motion_estimation_data
              drop: 3

      - topic: imu_data1
        valid_range: [0, 10]
        watchdog: 25
        invalid_input_callback:
          fault:
            affect_publish:
              topic: motion_estimation_data
              drop: 3

    loop:
      period: 25
      callback:
        publish:
          - topic: motion_estimation_data
            value_range: [500, 1000]
            delay_range: [2, 3]

  - name: landmark_recognizer
    subscribe:
      - topic: visual_odometry_data
        valid_range: [50, 100]
        watchdog: 12
        invalid_input_callback:
          fault:
            affect_publish:
              topic: landmark_data
              drop: 5

      - topic: obstacle_data
        valid_range: [50, 100]
        watchdog: 12
        invalid_input_callback:
          fault:
            affect_publish:
              topic: landmark_data
              drop: 5

      - topic: road_data
        valid_range: [20, 30]
        watchdog: 25
        invalid_input_callback:
          fault:
            affect_publish:
              topic: landmark_data
              value: 40
              count: 2
        lost_input_callback:
          fault:
            affect_publish:
              topic: landmark_data
              drop: 2

      - topic: map_data
        valid_range: [10, 20]
        watchdog: 25
        invalid_input_callback:
          fault:
            affect_publish:
              topic: landmark_data
              value: 30
              count: 2
        lost_input_callback:
          fault:
            affect_publish:
              topic: landmark_data
              drop: 2

    loop:
      period: 25
      callback:
        publish:
          - topic: landmark_data
            value_range: [500, 1000]
            delay_range: [2, 3]
