name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Bazel        
      uses: abhinavsingh/setup-bazel@v3
      with:
        version: 7.3.0
    - name: Analysing the code with pylint
      run: |
        ./lint.sh
